=== vhidalgop/Bryans-Cafe-xml-dtd/contact.dtd
<!ELEMENT contactInfo (location+)>
<!ELEMENT location (address, phone, hours)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT phone (#PCDATA)>
<!ELEMENT hours (#PCDATA)>

=== vhidalgop/Bryans-Cafe-xml-dtd/contact.xml
<!-- contact.xml -->
<!DOCTYPE contactInfo SYSTEM "contact.dtd">
<contactInfo>
    <location>
        <address>76 Devonshire St, Surry Hills, NSW</address>
        <phone>02 9211 1234</phone>
        <hours>Mon-Fri: 6:00 to 14:30, Sat-Sun: 7:00 to 15:00</hours>
    </location>
    <location>
        <address>451 Pitt St, Haymarket Sydney, NSW</address>
        <phone>02 9262 5678</phone>
        <hours>Mon-Fri: 6:00 to 16:00, Sat-Sun: 7:00 to 15:00</hours>
    </location>
    <location>
        <address>31 Alfred Street, Circular Quay, NSW</address>
        <phone>02 8971 9101</phone>
        <hours>Mon-Fri: 6:00 to 16:00, Sat-Sun: 7:00 to 15:00</hours>
    </location>
</contactInfo>
